version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    volumes:
      - ./conf.d/mariadb.cnf:/etc/mysql/my.cnf
    restart: always

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    links:
      - mariadb
      - redis
    depends_on:
      - mariadb

  redis:
    image: redis
    hostname: redis
